#!/opt/homebrew/bin/python3
import sys
import time

import discord
from discord.ext import commands

from src import serf 
from src.util import resolve_user_token, resolve_input

#----------------------------------------
# SET UP
#----------------------------------------
client = commands.Bot(
    command_prefix="$",
    self_bot=True,
    help_command=None,
    intents=None
)


#----------------------------------------
# DIAGNOSTICS
#----------------------------------------
@client.event
async def on_ready():
    print("Online")


@client.command()
async def musub(ctx, message):
    while True:
        await ctx.send(message)
        time.sleep(.25)


@client.command(pass_context=True)
async def diagnostic(ctx, message, start_date, target):
    #print(message)
    #print(start_date)
    #print(target)
    #print(ctx.channel)
    #print(ctx.history)
    #print(ctx.__class__)
    pass


@client.command()
async def k(ctx, collect_flags):
    scroll = await serf.reap(ctx, client.user, collect_flags)
    serf.people(scroll)
    return


#----------------------------------------
# COLLECTORS
#----------------------------------------
# Last Date | 2023-03-11 
#----------------------------------------
@client.command(pass_context=True)
async def sil(ctx, collect_flags, start_date=None, target=None):
    scroll = await collections(
        ctx,
        client.user,
        collect_flags,
        start_date,
        target
    )
    await serf.john_alite(ctx, scroll)
    return


@client.command()
async def col(ctx, collect_flags, writer_key, start_date=None, target=None):
    scroll = await collections(
        ctx,
        client.user,
        collect_flags,
        start_date,
        target
    )
    writer_key = int(writer_key)
    serf.writer(scroll, writer_key)
    return


#----------------------------------------
# HELPERS
#----------------------------------------
async def collections(
    ctx,
    user,
    collect_flags,
    start_date=None,
    target=None
):
    start_date, target = resolve_input(start_date, target)
    return await serf.reap(
        ctx,
        user,
        collect_flags,
        start_date,
        target
    )


#----------------------------------------
# END OF FILE
#----------------------------------------
if __name__ == "__main__":
    if len(sys.argv) < 2:
        print('Please invoke with username')
        exit()
    else:
        token = resolve_user_token(sys.argv[1])
        client.run(token, bot=False)
#----------------------------------------
# END OF END OF FILE
#----------------------------------------
