#!/opt/homebrew/bin/python3.10

import json
import sys, time
from typing import Any
import discord
from discord.ext import commands
from src import s, serf, chisel, studio 
from src.serf import C
from src.util import resolve_user_token, resolve_input
#----------------------------------------
# SET UP
#----------------------------------------
client = commands.Bot(
    command_prefix="™",
    self_bot=True,
    help_command=None,
    intents=None
)

COLLECTOR = None

@client.event
async def on_ready():
    COLLECTOR = C(client.user)
    print("Online")
#----------------------------------------
# Ma
#----------------------------------------
@client.command(pass_context=True)
async def note(ctx, target=None) -> None:
    collect_flags = "na"
    start_date = "09102023"
    await nott(ctx, collect_flags, start_date, target)


@client.command()
async def nott(ctx, collect_flags ,start_date, target=None) -> None:
    start_date, target = resolve_input(start_date, target)

    COLLECTOR.setup(ctx, start_date, target)
    await COLLECTOR.reap()

    # only using data available in all formats currently
    editor_key = 1
    chisel.editor(COLLECTOR.whisp_cache, editor_key)[0]

    COLLECTOR.teardown()


@client.command(pass_context=True)
async def delete(ctx, target=None) -> None:
    collect_flags = "nm"
    start_date = "09112023"
    await delet(ctx, collect_flags, start_date, target)


@client.command()
async def delet(ctx, collect_flags, start_date=None, target=None) -> None:
    start_date, target = resolve_input(start_date, target)
    COLLECTOR.setup(ctx, start_date, target)
    await COLLECTOR.reap()
    await serf.john_alite(COLLECTOR.whisp_cache)
    COLLECTOR.teardown()
#----------------------------------------
# DIPPERS 
#----------------------------------------
@client.command()
async def repeat(ctx, message):
    while True:
        await ctx.send(message)
        time.sleep(.5)


@client.command(pass_context=True)
async def diagnostic(ctx, message):
    #as needed
    print(dir(ctx))
    print(message)
    return


#@client.command()
#async def poll(ctx, collect_flags):
#    scroll = await serf.reap(ctx, client.user, collect_flags)
#    s.people(scroll)
#    return
#----------------------------------------
# COLLECTORS
#----------------------------------------
# Last Date | 2023-03-11 
#----------------------------------------


#@client.command()
#async def col(ctx, collect_flags, editor_key, start_date=None, target=None):
#    scroll = await collections(
#        ctx,
#        client.user,
#        collect_flags,
#        start_date,
#        target
#    )
#    editor_key = int(editor_key)
#    chisel.editor(scroll, editor_key)
#    return
#----------------------------------------
# TEST
#----------------------------------------

#@client.command()
#async def t():
#    guild = client.get_guild(873320575643312179)
#    print(guild)
#    channels = guild.channels
#    print(channels)

#----------------------------------------
# END OF FILE
#----------------------------------------
if __name__ == "__main__":
    if len(sys.argv) < 2:
        exit('Please invoke with username')
    else:
        token = resolve_user_token(sys.argv[1])
        client.run(token, bot=False)

#----------------------------------------
# END OF END OF FILE
#----------------------------------------
