#!/opt/homebrew/bin/python3.10

import json
import sys, time
from typing import Any
import discord
from discord.ext import commands
from src import s, serf, chisel, studio
from src.stalker import Stalker
from src.util import open_toml, resolve_user_token, resolve_input


name = lambda user: f"{user.display_name}"


def location(server):
    cname = str(server.get('channel'))
    sname = str(server.get('server'))
    return f"{cname}::{sname}"


#----------------------------------------
client = commands.Bot(
    command_prefix="¡",
    self_bot=True,
    help_command=None,
    intents=None
)


def start():
    global INTERN
    global CONFIG
    global SERVER
    global STALKER

    INTERN = serf.Intern(client.user)
    CONFIG = open_toml("servers")
    SERVER = None
    STALKER = None


@client.event
async def on_ready():
    start()
    print("Online")

@client.event
async def on_message_add(message):
    global STALKER
    if STALKER is not None:
        for message in STALKER.on_messages(message):
            if len(message) is not 0:
                studio.summaries(message)
            break

#@client.event
#async def on_reaction_add(reaction, user):
#    message = reaction.message
#    channel = message.channel
#    if message.author == client.user:
#        await channel.send(f"thank you {user} for reacting to my post. hope to see you soon!")

@client.event
async def on_raw_reaction_add(raw_reaction):
    global STALKER
    global SERVER
    if STALKER is not None and SERVER is not None:
        message: str | None = await STALKER.on_raw_react(raw_reaction, client)
        if message is not None:
             await SERVER.get("channel").send(message)


@client.command()
async def reset_cfg(_ctx) -> None:
    global CONFIG
    CONFIG = open_toml("servers")


@client.command()
async def where(ctx) -> None:
    _ctx = str(ctx)
    print(dir(ctx))
    #await ctx.send(_ctx)


#----------------------------------------
@client.command()
async def which_channel(ctx, flag=None) -> None:
    global SERVER
    if SERVER is not None:
        await ctx.send(f"Now connected to: {location(SERVER)}")
    else:
        await ctx.send("Not connected currently")
        if flag == "l":
            channels = "\n".join(f"{s}" for s in CONFIG.get("servers"))
            await ctx.send(f"list: \n{channels}")


@client.command()
async def set_channel(ctx, server) -> None:
    global SERVER
    server: int | None = CONFIG.get("servers", {}).get(server)

    if server is not None:
        channel_id: int | None = server.get("gen")
        guild_id: int | None = server.get("id")

        SERVER = {'channel': client.get_channel(channel_id),
                  'server': client.get_guild(guild_id)}
        await ctx.send(f"Now connected to: {location(SERVER)}")
    else:
        await ctx.send("Channel not found")


@client.command()
async def reset_channel(ctx) -> None:
    global SERVER
    if SERVER is not None:
        await ctx.send(f"Disconnecting from: {location(SERVER)}")
    SERVER = None


@client.command()
async def sendto(ctx, *args) -> None:
    global SERVER
    if SERVER is not None:
        channel = SERVER.get('channel')
        message = " ".join(args)
        await channel.send(message)
    else:
        await ctx.send("Not connected currently")


#----------------------------------------
@client.command()
async def which_user(ctx) -> None:
    global STALKER
    if STALKER is not None:
        await ctx.send(f"Now stalking {name(STALKER.user)}")
    else:
        await ctx.send("No target currently")


@client.command()
async def set_user(ctx, message: str) -> None:
    global STALKER
    try:
        user_id = int(message)
    except:
        await ctx.send(f"Poorly formatted user_id: {message}")
        return

    user: Any = await client.fetch_user(user_id)
    u_n = name(user)

    if STALKER is not None:
        await ctx.send(f"Switching target from {name(STALKER.user)} to {u_n}")
    else:
        await ctx.send(f"Target set to {u_n}")
    STALKER = Stalker(user)


@client.command()
async def reset_user(ctx) -> None:
    global STALKER
    if STALKER is not None:
        await ctx.send(f"Saying goodbye to: {name(STALKER.user)}")
    STALKER = None


#----------------------------------------
@client.command(pass_context=True)
async def note(ctx) -> None:
    collect_flags = "an"
    start_date = "09102023"
    await nott(ctx, collect_flags, start_date)


@client.command()
async def nott(ctx, collect_flags, start_date, target=None) -> None:
    start_date, target = resolve_input(start_date, target)
    channel = SERVER.get("channel") if SERVER.get("channel") is not None else ctx.channel
    INTERN.setup(collect_flags,channel, start_date, target)
    await INTERN.reap()
    # only using data available in all formats currently
    chisel.editor(INTERN.whisp_cache, 1) # editor_key
    INTERN.reset()


@client.command(pass_context=True)
async def delete(ctx) -> None:
    collect_flags = "mn"
    start_date = "01282024"
    await delet(ctx, collect_flags, start_date)


@client.command()
async def delet(ctx, collect_flags, start_date=None, target=None) -> None:
    start_date, target = resolve_input(start_date, target)
    channel = SERVER.get("channel") if SERVER.get("channel") is not None else ctx.channel
    INTERN.setup(collect_flags, channel, start_date, target)
    await INTERN.reap()
    await INTERN.shred()
    INTERN.reset()


#----------------------------------------
@client.command()
async def repeat(ctx, message):
    while True:
        await ctx.send(message)
        time.sleep(.5)


@client.command(pass_context=True)
async def diagnostic(ctx, message):
    #as needed
    print(dir(ctx))
    print(message)
    return


#@client.command()
#async def poll(ctx, collect_flags):
#    scroll = await serf.reap(ctx, client.user, collect_flags)
#    s.people(scroll)
#    return
#----------------------------------------
# TEST
#----------------------------------------
#@client.command()
#async def t():
#    guild = client.get_guild(873320575643312179)
#    print(guild)
#    channels = guild.channels
#    print(channels)
#----------------------------------------
# END OF FILE
#----------------------------------------
if __name__ == "__main__":
    if len(sys.argv) < 2:
        exit('Please invoke with username')
    else:
        token = resolve_user_token(sys.argv[1])
        client.run(token, bot=False)

#----------------------------------------
# END OF END OF FILE
#----------------------------------------
